export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const REQUESTING = "REQUESTING";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const ADD_USER_ATTENDANCE_REQUEST = "ADD_USER_ATTENDANCE_REQUEST";
export const ADD_USER_ATTENDANCE_SUCCESS = "ADD_USER_ATTENDANCE_SUCCESS";
export const ADD_USER_ATTENDANCE_FAILURE = "ADD_USER_ATTENDANCE_FAILURE";

export const GET_USER_ATTENDANCE_REQUEST = "GET_USER_ATTENDANCE_REQUEST";
export const GET_USER_ATTENDANCE_SUCCESS = "GET_USER_ATTENDANCE_SUCCESS";
export const GET_USER_ATTENDANCE_FAILURE = "GET_USER_ATTENDANCE_FAILURE";
